/**
 * Auto-generated RPC Permission Map
 *
 * DO NOT EDIT MANUALLY - This file is generated by extract-permissions.ts
 * Generated at: 2026-01-10T13:49:05.797Z
 *
 * Maps RPC endpoints to their required permission strings.
 * Endpoints not listed here are considered public (no permission required).
 */

/**
 * Map of RPC endpoint paths to required permissions.
 */
export const rpcPermissions: Record<string, string> = {
  "/sales/sales_flow/deliverSalesOrder": "sales.flow.deliver"
};

/**
 * Gets the required permission for an endpoint.
 * Returns null if no permission is required (public endpoint).
 */
export function getRequiredPermission(endpoint: string): string | null {
  return rpcPermissions[endpoint] ?? null;
}

/**
 * Checks if an endpoint requires authentication.
 */
export function isProtectedEndpoint(endpoint: string): boolean {
  return endpoint in rpcPermissions;
}
