version: "3"

services:
  db:
    container_name: db-agape-dev
    image: "postgres:14"
    environment:
      POSTGRES_PASSWORD: "mypassword"
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:7.4
    container_name: pgadmin4-dev
    restart: always
    ports:
      - "8080:80"
    environment:
      - "PGADMIN_DEFAULT_EMAIL=admin@mapineda48.com"
      - "PGADMIN_DEFAULT_PASSWORD=admin"
    depends_on:
      - db

  azurite:
    container_name: azurite-dev
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000" # Blob service
      - "10001:10001" # Queue service (opcional)
      - "10002:10002" # Table service (opcional)
    command: >
      azurite-blob --blobHost 0.0.0.0 --blobPort 10000 --location /data
    volumes:
      - azurite-data:/data

  redis:
    container_name: redis-dev
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  azurite-data:
  redis-data:
