#cloud-config
package_update: true
package_upgrade: true

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - software-properties-common
  - fuse3

write_files:
  - path: /etc/fuse.conf
    append: true
    content: |
      user_allow_other

runcmd:
  # Instalar Docker
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
  - apt-get update
  - apt-get install -y docker-ce docker-ce-cli containerd.io

  # Crear grupo fuse si no existe y agregar usuario a grupos necesarios
  - groupadd --system fuse || true
  - usermod -aG docker azureuser
  - usermod -aG fuse azureuser

  # Instalar Blobfuse2
  - curl -L https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb -o packages-microsoft-prod.deb
  - dpkg -i packages-microsoft-prod.deb
  - apt-get update
  - apt-get install -y blobfuse2

  # Crear punto de montaje
  - mkdir -p /mnt/deploy
  - chown azureuser:docker /mnt/deploy
  - chmod 775 /mnt/deploy

  # Iniciar blob2
  - blobfuse2 mount /mnt/deploy --config-file=/etc/agape.js/blobfuse2.yaml --allow-other

  # Crear carpetas necesarias
  - mkdir -p /mnt/deploy/vm/agape.js/docker/certs
  - mkdir -p /mnt/deploy/vm/agape.js/docker/vhost.d
  - mkdir -p /mnt/deploy/vm/agape.js/docker/html

  # Permisos para que grupo docker acceda a los volúmenes
  - chown -R azureuser:docker /mnt/deploy/vm/agape.js
  - chmod -R 775 /mnt/deploy/vm/agape.js

  # Habilitar el servicios
  - systemctl enable --now mapineda48-blobfuse2-deploy
  - systemctl enable --now mapineda48-docker-compose
  - systemctl enable --now mapineda48.socket

  # Reiniciar la VM para aplicar cambios de grupos
  - reboot