/**
 * Socket Namespace Permissions (AUTO-GENERATED)
 *
 * DO NOT EDIT MANUALLY - This file is generated by extract-permissions.ts
 * Generated at: ${new Date().toISOString()}
 *
 * Maps Socket.IO namespace paths to their required permission strings.
 * Namespaces not listed here require authentication but no specific permission.
 */

// ============================================================================
// Socket Namespace Permissions
// ============================================================================

/**
 * Map of Socket.IO namespace paths to required permissions.
 */
export const socketPermissions: Record<string, string> = {
  // Auto-generated entries will be added here
};

/**
 * Gets the required permission for a namespace.
 * Returns null if no specific permission is required.
 */
export function getRequiredPermission(namespace: string): string | null {
  return socketPermissions[namespace] ?? null;
}

/**
 * Checks if a namespace requires a specific permission.
 */
export function isProtectedNamespace(namespace: string): boolean {
  return namespace in socketPermissions;
}
