ALTER TABLE "agape_app_development_demo"."numeration_document_sequence" ALTER COLUMN "assigned_date" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "agape_app_development_demo"."numeration_document_series" ALTER COLUMN "valid_from" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "agape_app_development_demo"."numeration_document_series" ALTER COLUMN "valid_to" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "agape_app_development_demo"."inventory_movement_type" ADD COLUMN "document_type_id" integer NOT NULL;--> statement-breakpoint
ALTER TABLE "agape_app_development_demo"."inventory_movement" ADD COLUMN "document_series_id" integer NOT NULL;--> statement-breakpoint
ALTER TABLE "agape_app_development_demo"."inventory_movement" ADD COLUMN "document_number" integer NOT NULL;--> statement-breakpoint
ALTER TABLE "agape_app_development_demo"."inventory_movement" ADD COLUMN "document_number_full" varchar(50) NOT NULL;--> statement-breakpoint
ALTER TABLE "agape_app_development_demo"."inventory_movement_type" ADD CONSTRAINT "inventory_movement_type_document_type_id_numeration_document_type_id_fk" FOREIGN KEY ("document_type_id") REFERENCES "agape_app_development_demo"."numeration_document_type"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "agape_app_development_demo"."inventory_movement" ADD CONSTRAINT "inventory_movement_document_series_id_numeration_document_series_id_fk" FOREIGN KEY ("document_series_id") REFERENCES "agape_app_development_demo"."numeration_document_series"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "ux_inventory_movement_series_number" ON "agape_app_development_demo"."inventory_movement" USING btree ("document_series_id","document_number");