/**
 * Permissions Configuration
 *
 * This file contains two types of permissions:
 *
 * 1. **Navigation Permissions (CONSTANT)** - Manually defined permissions for
 *    module access/navigation. These control what users can see in the menu
 *    and which routes they can access.
 *
 * 2. **RPC Permissions (AUTO-GENERATED)** - Extracted from @permission JSDoc
 *    tags in service files. DO NOT EDIT the rpcPermissions section manually.
 *
 * Generated at: 2026-01-10T13:49:05.797Z
 */

// ============================================================================
// Navigation Permissions (CONSTANT - Edit these manually)
// ============================================================================

/**
 * Constant permissions for module navigation/view access.
 * These permissions control what users can see in the sidebar menu
 * and which routes they are allowed to access.
 *
 * Convention: `{module}.view` for read-only module access
 *
 * IMPORTANT: Edit this section to add/remove navigation permissions.
 */
export const navigationPermissions = {
  // Core CMS access
  "cms.view": "Acceso básico al CMS",
} as const;

/**
 * Type representing all valid navigation permission keys.
 */
export type NavigationPermission = keyof typeof navigationPermissions;

/**
 * Array of all navigation permission keys for iteration.
 */
export const navigationPermissionKeys = Object.keys(
  navigationPermissions,
) as NavigationPermission[];

// ============================================================================
// RPC Permissions (AUTO-GENERATED - Do not edit manually)
// ============================================================================

/**
 * Map of RPC endpoint paths to required permissions.
 * This section is auto-generated by extract-permissions.ts from @permission JSDoc tags.
 *
 * DO NOT EDIT MANUALLY - Changes will be overwritten during generation.
 */
export const rpcPermissions: Record<string, string> = {
  "/sales/sales_flow/deliverSalesOrder": "sales.flow.deliver",
};

// ============================================================================
// Combined Permissions
// ============================================================================

/**
 * All permissions available in the system.
 * Combines navigation permissions with RPC permissions.
 */
export const allPermissions: Record<string, string> = {
  ...navigationPermissions,
  ...rpcPermissions,
};

/**
 * Gets the required permission for an RPC endpoint.
 * Returns null if no permission is required (public endpoint).
 */
export function getRequiredPermission(endpoint: string): string | null {
  return rpcPermissions[endpoint] ?? null;
}

/**
 * Checks if an RPC endpoint requires authentication.
 */
export function isProtectedEndpoint(endpoint: string): boolean {
  return endpoint in rpcPermissions;
}

/**
 * Checks if a permission key is valid (exists in the system).
 */
export function isValidPermission(permission: string): boolean {
  return permission in allPermissions;
}

/**
 * Gets all permission keys as an array.
 */
export function getAllPermissionKeys(): string[] {
  return Object.keys(allPermissions);
}
