#cloud-config
package_update: true
package_upgrade: true
packages:
  - curl
  - ca-certificates
  - gnupg
  - lsb-release

runcmd:
  - mkdir -m 0755 -p /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  - echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
      $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  - apt-get update
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  - usermod -aG docker azureuser
  - systemctl enable docker
  - systemctl start docker

write_files:
  - path: /home/azureuser/docker-compose.yml
    permissions: '0644'
    owner: azureuser:azureuser
    content: |
      version: "3.9"

      services:

        nginx-proxy:
          image: nginxproxy/nginx-proxy:1.2
          container_name: proxy-pomi
          ports:
            - "80:80"
            - "443:443"
          volumes:
            - certs:/etc/nginx/certs
            - vhost:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
            - /var/run/docker.sock:/tmp/docker.sock:ro

        nginx-proxy-acme:
          image: nginxproxy/acme-companion:2.2
          container_name: acme-pomi
          volumes_from:
            - nginx-proxy
          volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - acme:/etc/acme.sh
          environment:
            DEFAULT_EMAIL: ${DEFAULT_EMAIL}
            ACME_CA_URI: https://acme-staging-v02.api.letsencrypt.org/directory

        app:
          image: mapineda48/msgpack-vite-agape-app
          container_name: agape-app-demo
          environment:
            VIRTUAL_HOST: ${VIRTUAL_HOST}
            DATABASE_URI: ${DATABASE_URI}
            AZURE_CONNECTION_STRING: ${AZURE_CONNECTION_STRING}
          depends_on:
            - nginx-proxy

      volumes:
        certs:
        vhost:
        html:
        acme:
        data:
