/**
 * Type declarations for Socket.IO virtual modules
 * 
 * These stubs provide type information for @agape/*.socket virtual modules
 * generated by Vite. The actual implementation is generated at build time.
 */

/** Event handler function signature */
type EventHandler = (...args: unknown[]) => void;

/** RPC method function signature */
type RpcMethod = (...args: unknown[]) => Promise<unknown>;

/** Connected socket interface */
export interface ConnectedSocket {
    /** Disconnect from the socket */
    disconnect: () => void;
    /** Subscribe to server events */
    on: (event: string, handler: EventHandler) => void;
    /** Unsubscribe from server events */
    off: (event: string, handler?: EventHandler) => void;
    /** Call an RPC method by name */
    call: (method: string, ...args: unknown[]) => Promise<unknown>;
    /** Dynamic RPC methods added at runtime */
    [key: string]: RpcMethod | EventHandler | (() => void);
}

/** Socket client factory interface */
export interface SocketClientFactory {
    connect: () => ConnectedSocket;
}

/** Default export is a socket client factory */
declare const socketClient: SocketClientFactory;
export default socketClient;
